### PR TITLE
Complete getMeeting() when user leaves meeting

### PR DESCRIPTION
**Pull request by lalli-flores**

### CODE REVIEW

**Comment by akoushke** [comment]
upgrade the interface.

**Comment by akoushke** [comment]
also remove the `addLocalMedia` method from the adapters

**Comment by lalli-flores** [comment]
> upgrade the interface.

done

**Comment by lalli-flores** [comment]
> also remove the `addLocalMedia` method from the adapters

No need to remove it, it's a helper method so it can be called whatever.

**Comment by akoushke** [comment]
GOOD JOB LALLI! WELL WELL DONE!

**Pull request merged**
