### PR TITLE
Helper Component refactor

### PR DESCRIPTION
**Pull request by lalli-flores**
Moving out helper components make code more modular and easier to read.

### Issues
I realized we did not have enough unit test/snapshots for the `TimeRuler` component, but right now the formatting function is not working properly, at least on my environment.

### CODE REVIEW

**Comment by akoushke** [comment]
I shared the _mocks_ directory with you

**Comment by akoushke** [comment]
fix the lint problems.

**Comment by akoushke** [comment]
we could open this back again later.

**Comment by lalli-flores** [comment]
For readability/review-ability, I will be splitting the refactoring into multiple PRs:
Webex Activity + unite test date fix: https://github.com/webex/components/pull/47

**Pull request closed without merging**
