### PR TITLE
Webex In-Meeting style fixes

### PR DESCRIPTION
**Pull request by lalli-flores**

### CODE REVIEW

**Comment by lalli-flores** [comment]
> Screen Shot 2020-02-25 at 10 49 00 AM
> LGTM. this should be fix in #83 i'm assuming?

Yeah, those would be local media styles

**Comment by akoushke** [comment]
Screen Shot 2020-02-25 at 10 51 06 AM
looks a bit iffy in FF :/

**Comment by lalli-flores** [comment]
> Screen Shot 2020-02-25 at 10 51 06 AM
> looks a bit iffy in FF :/
> 
> not a blocker.

Also fixed by Webex Local Media styles 🙂

**Pull request merged**
