### PR TITLE
refactor(WebexInMeeting): add separate stories for share

### PR DESCRIPTION
**Pull request by alinasuciu**
Add separate stories for local share and remote share in WebexInMeeting component

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-227223

### CODE REVIEW

**Review by cipak — APPROVED** [review]

**Comment by lalli-flores** [comment]
Seems like some the changes assume https://github.com/webex/components/pull/208 to be in the code base?

**Comment by alinasuciu** [comment]
> Seems like some the changes assume #208 to be in the code base?



> Seems like some the changes assume #208 to be in the code base?

Not necessarily, but it would be good otherwise I think that we should re-generate the storyshots

**Review by lalli-flores — APPROVED** [review]

**Comment by alinasuciu** [comment]
Screenshot 2021-04-27 161010
Screenshot 2021-04-27 161044

**Comment by lalli-flores** [comment]
This is so cool! Thanks @alinasuciu 🙌🏼

**Pull request merged**
